// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATDOB1Gw8Ke5L60pzM47_s44sxKQfGYj8',
    appId: '1:280962085515:web:b323e4fc7141f2db7c5a8e',
    messagingSenderId: '280962085515',
    projectId: 'flutter3012',
    authDomain: 'flutter3012.firebaseapp.com',
    storageBucket: 'flutter3012.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAonZTFYS5xqtDNBkkxs4Jbd3gcL8KceDg',
    appId: '1:280962085515:android:073ae20f5d15e61c7c5a8e',
    messagingSenderId: '280962085515',
    projectId: 'flutter3012',
    storageBucket: 'flutter3012.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATDOB1Gw8Ke5L60pzM47_s44sxKQfGYj8',
    appId: '1:280962085515:web:d3a34e6a9bab60b87c5a8e',
    messagingSenderId: '280962085515',
    projectId: 'flutter3012',
    authDomain: 'flutter3012.firebaseapp.com',
    storageBucket: 'flutter3012.appspot.com',
  );
}
